services:
  mongodb:
    image: mongo:8
    container_name: mongodb

    profiles:
      - mongo

    restart: unless-stopped

    ports:
      - "${MONGO_PORT}:27017"

    volumes:
      - ../data/mongodb:/data/db

    networks:
      - dev-network

  redis:
    image: redis:8
    container_name: redis

    profiles:
      - redis

    restart: unless-stopped

    ports:
      - "${REDIS_PORT}:6379"

    volumes:
      - ../data/redis:/data

    networks:
      - dev-network

networks:
  dev-network: